Pet-Mate-Project/Pet-Mate

- src/components/user/User.jsx
- src/template/snsPost/SnsPost.jsx
- src/template/snsPost/snsPostStyle.js
- 반응형으로 제작하여 화면 넓이에 비례하여 이미지 높이가 조정됩니다. vw사용
- postText의 경우 word-break : keep-all 속성을 사용하여 단어별로 글자가 끊겨 사용자가 더 보기 편하도록 구현 하였습니다.
- postText 또한 화면 넓이에 비례하여 넓이가 조정됩니다. 
- PostText - img, Icon - Img 사이 마진 간격 조정 (추가 커밋)
( 예시 이미지는 글로벌 스타일이 적용되지 않은 이미지로 마진간격이 약간 다를 수 있습니다.)
close #54
> 💄 Add : SnSPost 컴포넌트 구현

- src/components/animalBox/AnimalBox.jsx
- src/components/animalBox/animalStyle.js
- src/pages/MyProfilePage.jsx
- src/template/profilePost/PetPost.jsx
- src/template/profilePost/petPostStyle.js
##등록한 펫 리스트 템플릿 추가 
- Myprofile 에서 보이는 펫 등록 리스트 추가
- 구현하면서 관련 컴포넌트 스타일 값 수정
- 스크롤하면 나머지 리스트 보이도록 구현
- 스크롤바는 안보이게 했습니다
- 보더 디자인은 임의로 포스트 구분선과 비슷하게 해놓았습니다 (개인적으로 회색보다는 이게 나았습니당 다른 의견 있으시면 얘기해주세요!)
2commits
- 산책피드에 게시글이 없는경우 PetPost가 랜더링되지않습니다
close #146
> :lipstick: Add : Myprofile 하단부분 등록한 펫 리스트 추가

- src/App.js
- src/components/navBack/NavBack.jsx
- src/pages/FeedPage.jsx
- src/pages/HomePage.jsx
- 검색하기(`textBtn`) 버튼과 아이콘(`searchbar`)을 클릭했을 때 `/search` 페이지로 이동하도록 구현하였습니다.
<br>
- 아이콘(`searchbar`)을 클릭했을 때 `/search` 페이지로 이동하도록 구현하였습니다.
<br>
close #150
> :sparkles: Feat : Search페이지 라우팅 연결

- src/template/snsPost/AddSnsPost.jsx
- 여러개의 이미지를 업로드시 브라우저 상에서 미리볼수 있는 기능 구현
- `createObjectURL` 사용
[preview]
- 한장씩 업로드시 최대 3장까지 추가
- 여러장을 동시에 업로드 할 수 있음
- 3장이 넘어가면 alert창이 드고 순서대로 3장만 렌더링
(사진 클릭하는 부분이 안보이긴 하지만 사진을 클릭하고 있습니다 ㅎㅎ,,)
close #153
> :sparkles: Feat : 여러이미지업로드(미리보기)

- src/components/animalBox/animalStyle.js
- src/components/profileIcon/ProfileIcon.jsx
- src/components/profileIcon/profileIconStyle.js
- src/pages/SignUpMain.jsx
- src/style/commonStyle.js
- src/template/profilePost/petPostStyle.js
- src/template/signUp/ProfilePage.jsx
- 스크롤 바 스타일 변경 
기존 스크롤 바 없음에서 스타일 변경한 스크롤 바로 변경
- 프로필 이미지 원형으로 변경
(게시글 포스팅 프로필이미지 사각형 -> 원형 변경
- 프로필 펫등록 포스팅 반응형
페이지 넓이에 따른 펫등록 포스팅 이미지 넓이 변경
- 스크롤 메인 컴포넌트에도 동일한 스크롤 디자인 적용
> 💄 Style : 스크롤바 스타일변경, 프로필이미지 원형으로 변경,  프로필펫등록 포스팅 반응형

- src/App.js
- src/components/followCompo/FollowCompo.jsx
1. `/`  :  splash 페이지
2. `/login` : 로그인페이지
3. `/join` : 회원가입 페이지
- token값 여부에 따라 조건부렌더링
- token값이 없다면 전부 splash로 리다이렉트
1. `/homepage` :  펫 정보가 올라간 게시글
2. `/feedpage` : 소통하는 sns게시글
3. `/profilepage` : 내프로필페이지 / 펫정보게시글,소통게시글 둘다있음
4. `/profilemodify` : 내 프로필 수정페이지
5. `/post` :  반려정보 게시글 등록하는 페이지
6. `/snspost` : 자유소통게시글 등록
7. `/chatpage` :  채팅목록페이지
8. `/search` :  유저계정검색 페이지 
9. `/follow` :  팔로우 한 유저정보가 있는 페이지
10. `/chatroom` : 채팅방페이지
- 404page
- 404page 뒤로가기 onClick이벤트 구현
close #165
> :sparkles: Feat : url로 직접 접근시 조건부렌더링

- src/template/profilePost/MyProfileSnsPost.jsx
- src/template/profilePost/SnsAlbum.jsx
- src/template/profilePost/SnsAlbumStyle.js
- 화면 비율 이슈
일정한 비율을 주고싶었는데, grid row를 정해주자니 게시글이 특정 갯수 이상 올렸을때 UI가 깨지게 되어 row는 정해주지 않은채로 높이를 픽스해주었습니다 
우선 화면 넓이에 따른 3단계 변화로 구현하였는데 피드백 부탁드립니다! 
close #168
> :sparkles: Feat : 마이페이지 내게시글 랜더링 앨범형까지 구현완료

- src/pages/MyProfilePage.jsx
- `dispatch`를 추가하여 게시글렌더링버그 해결
- RTK사용하셔서 불러오실때  dispatch로 axios요청을 해야 결과값이 들어와서 게시글이 렌더링 됩니당!! 참고부탁 드려요ㅎㅎ
(sns게시글 피드에는 dispatch가 되어있어서 axios요청을 받기때문에 게시글피드에 들어갔다가 마이프로필에 들어가면 store에 있는 정보를 그대로 렌더링이 되서 렌더링 된겁니다! )
> :sparkles: Add : dispatch를 추가하여 게시글렌더링버그 해결

- src/components/profile/Profile.jsx
프로필 업로드 시 10mb 이상의 파일의 경우 
에러 발생하여 최대 용량 제한으로 해결
- 10mb이상의 파일이 업로드 되면  alert 출력 후 이미지 등록 취소됨. 이후 초기 사용자 프로필 이미지로 변경 
- 회원 가입, 프로필 수정 모두 적용 / 회원 가입의 경우 기본 이미지로 취소 됨
close #172
> :bug: Modify : 프로필 사진 업로드 최대용량 제한

- src/components/user/User.jsx
* 팔로워/팔로잉 리스트에 있는 사용자의 이미지, 이름, 아이디 영역을 클릭했을 때 
해당 사용자의 프로필로 이동하도록 라우팅 설정
close #211
> :sparkles: Add : 팔로워/팔로잉 리스트에서 리스트 클릭시 해당 유저 프로필로 이동

- src/components/user/User.jsx
* 다른 사용자가 로컬에서 올린 프로필 이미지가 다른 사용자에게는 url문제로 보이지 않는 버그 수정
close #221
> :bug: Modify : 프로필 이미지가 뜨지않는 문제 수정

- src/App.js
- src/components/comment/Comment.jsx
- src/components/comment/commentStyle.js
- src/components/post/FeedPost.jsx
- src/components/post/feedPostStyle.js
- src/reducers/getPostDetailSlice.js
- src/template/postDetail/FeedPostDetail.jsx
- src/template/postDetail/FeedPostDetailStyle.js
- src/template/profilePost/MyProfileSnsPost.jsx
- src/template/snsFeed/SnsFeed.jsx
- src/template/snsPost/SnsPost.jsx
<첫번째 커밋> 
* 게시글 컴포넌트(FeedPost.jsx) 수정, 이에 따라 SnsPost.jsx내부 함수2개 -> 1개로 축소
* 상세페이지에 적용가능하도록  Comment컴포넌트와 스타일 수정
*  getPostDetailSlice.js에 구현되어 있는 게시글 상세 API를 통해 각 게시글 상세페이지 랜더링
close #243 
<br><br>
<두번째 커밋>
* 현재 useSelector를 통해 getPostDetailSlice.js의 게시글 상세페이지 API에서 데이터를 받아오고 이를 postDetail에 저장하고 있는 로직임. 
* 여기서 postDetail은 랜더링에 필요한 props인데, 데이터가 갱신되는 속도 차이로 인해 
다른 게시글 상세페이지에서 이전에 들어갔던 게시글의 데이터가 처음에 랜더링 되는 문제를 수정하였음.
close #245
> :sparkles: Feat : 게시글 상세페이지 구현

- src/components/user/User.jsx
- src/template/search/AccountSearch.jsx
- 계정 검색 결괏값과 일치하는 `useName`은 색상이 `#404040` -> `#1D57C1` 바뀌도록 구현하였습니다.
- `useId`는 색상이 변경되지 않습니다.
- 가독성의 이유로 아래  컴포넌트 `props` 코드 구조를 변경(줄바꿈) 하였습니다.
- `NavTxtSearch`, `Link`,  `User` 
<br>
close #175
> :sparkles: Feat : 계정 검색 결과와 일치하는 문자 색상 변경

- src/components/errorMessage/errorStyle.js
- src/template/search/AccountSearch.jsx
- 계정 검색 입력란에 값을 지워도 결괏값이 비어있지 않고 남아있는 것을 확인할 수 있었습니다.
- 검색 입력값이 비어있다면 `사용자 계정 또는 이름을 입력해 주세요.` 메시지를 출력하도록 수정하였습니다.
<br>
close #248
> :bug: Modify : 계정 검색 결괏값 출력

- src/App.js
- src/components/post/FeedPost.jsx
- src/reducers/getPostDetailSlice.js
- src/template/homePost/HomePost.jsx
- src/template/postDetail/FeedPostDetail.jsx
- src/template/postDetail/WalkingPostDetail.jsx
- src/template/postDetail/walkingPostDetailStyle.js
- src/template/profilePost/PetPost.jsx
* 산책게시글 상세페이지 UI 및 게시글 데이터 랜더링 구현
* 산책게시글 상세페이지의 url주소와 헷갈리지않기 위해 피드게시글 상세페이지 url주소 구체적으로 변경
* myprofile에서 산책게시글 클릭시 모달이 뜨는데 모달3번째 리스트에 상세페이지로 이동할 수 있도록 구현
* yourprofile에서는 산책게시글 클릭시 바로 상세페이지로 이동할 수 있도록 설정
close #260
> ✨ Feat : 산책(펫)게시글 상세페이지 구현 

- src/style/commonStyle.js
- src/style/globalStyle.js
- src/template/profilePost/SnsAlbum.jsx
1 commit
* myprofile과 yourprofile의 sns게시글에서 앨범형일 때 이미지 클릭시 해당 게시글의 상세페이지로 이동할 수 있도록 링크 연결 
<br>
2 commit
* 세로 스크롤로 인하여 랜더링될 때 레이아웃이 밀리는 현상이 있으므로 안보이도록 설정
* <Link>태그로 묶인 게시글들이 링크 태그의 속성때문에 이미 방문한 게시글의 텍스트는 보라색으로, 방문하지않은 게시글의 텍스트는 파란색으로 뜨는 부분이 없도록 속성 수정
<br><br>
close #274
> ✨ Add : 앨범형 게시글 클시 상세페이지로 이동

- src/components/input/inputStyle.js
- 사용자 가독성을 위해 InputStyle, TextAreaStyle 스타일 컴포넌트에 `padding-left: 4px` 추가했습니다.
<br>
<br>
<br>
<br>
<br>
close #276
> :lipstick: Style : Input 안쪽여백 추가

- src/components/post/FeedPost.jsx
- src/components/post/feedPostStyle.js
- src/components/user/userStyle.js
- src/template/homePost/homePostStyle.js
- src/template/postDetail/walkingPostDetailStyle.js
- src/template/profile/ProfileStyle.js
* 홈페이지, 피드페이지에서의 게시글에서는 텍스트가 길 경우 최대 3줄까지만 보이고 나머지는 말줄임표로 표시되도록 구현
* 상세페이지에서도 보기 편하도록 각 말줄임표 속성 적용
* 프로필에서 사용자 이름 및 소개 부분에서 과하게 길 경우를 방지하여 말 줄임표 적용
* 유저 정보가 보이는 NavBack에서 사용자 이름이 길 경우 말줄임표 적용
close #327
> :lipstick: Modify : 홈페이지, 피드페이지에서 게시글에 말줄임표 적용

- src/components/tabMenu/TabMenu.jsx
- src/pages/HomePage.jsx
- 사용자가 서비스를 이용하는데 헷갈릴 수 있는 메뉴 이름을 명확하게 구분할 수 있도록 수정하였습니다.
- `산책 피드` -> `산책 가까?` 변경 하였습니다.
- `피드` -> `SNS` 변경 하였습니다.
<br>
close #343
> :lipstick: Modify : 메뉴 이름 변경

- src/template/follow/MyFollow.jsx
- src/template/follow/YourFollow.jsx
* 팔로워/팔로잉 페이지에서의 모달창에서 로그아웃버튼을 클릭하면 useLocation()의 state값이 undefined되면서 에러가 생김. 
* 이 문제 해결하기 위해 옵셔널체이닝 사용하였음.
close #357
> :bug: Modify : 팔로워/팔로잉 페이지에서 로그아웃 클릭시 생기는 state에러

- src/template/search/AccountSearch.jsx
* 계정검색에서 자기 자신을 검색해서 클릭했을 때는 myprofile로 넘어가도록 삼항연산자를 추가
(동영상 밑에 있는 탭에서 프로필로 넘어가는 것을 확인할 수 있음)
close #365
> :bug: Modify : 로그인한 사용자 자신을 검색하여 클릭했을때, myprofile로 넘어가도록 라우팅 설정

- src/components/commentList/CommentList.jsx
- src/components/commentList/commentListStlye.js
* SNS게시글 상세페이지에 존재하는 댓글의 프로필정보를 클릭하면 해당 사용자의 프로필페이지로 이동할 수 있도록 구현
close #370
> :sparkles: Add : 댓글클릭시 유저프로필 페이지로 이동하도록 라우팅 설정
