Pet-Mate-Project/Pet-Mate

src/App.js
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/style/globalColor.js

Input 컨포넌트 구현 및 globalColor palette 세팅
close #6

:sparkles: Feat : Input 컴포넌트 구현

---

.eslintrc.json

:adhesive_bandage: Modify : eslint 코드추가

---

src/components/profile/profileStyle.js

업로드이미지 변수명 변경 및 background url 중복 삭제

:adhesive_bandage: Modify : 프로필 이미지 관련 코드 수정

---

src/components/input/Input.jsx
src/pages/singUp/signUp.js
src/pages/singUp/signUpStyle.jsx

* 회원가입 페이지 UI 구현 (민주, 세영 페어프로그래밍)
close #17

✨ Feat : 회원가입 UI  구현

---

src/components/button/Button.jsx
src/pages/login/Login.jsx
src/pages/login/loginStyle.js

* 로그인 페이지 UI 구현 (민주, 세영 페어프로그래밍)
close #19

✨ Feat : 로그인 페이지 UI 구현

---

src/App.js
src/components/button/Button.jsx
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/components/profile/profileStyle.js
src/pages/main/mainStyle.js
src/pages/sign-up/ProfilePage.jsx
src/pages/sign-up/profilePageStyle.js

:lipstick: Feat : 회원가입 프로필설정 UI 구현

---

.eslintrc.json
src/components/button/Button.jsx
src/components/input/Input.jsx
src/components/input/inputStyle.js

:lipstick: Modify : Button , input 컴포넌트 수정

---

src/components/button/Button.jsx

:lipstick: Modify : Button 컴포넌트 수정

---

src/components/errorMessage/errorMessage.jsx
src/components/errorMessage/errorStyle.js

errorMessage 컴포넌트 및 스타일(correct, error) 추가
close #29

:lipstick: Add : errorMessage 컴포넌트 추가

---

src/pages/login/Login.jsx

- 로그인 검증 후 JSON Payload를 localStorege에 저장
- 요거 승인해주시면 pull받고 라우팅 시작하겠습니당 ,, 
- 라우팅할때 파일들을 몇개를 건들지 몰라서 일단 토큰값 저장하는 코드 먼저 푸시 했습니다.

:sparkles: Add : Token 로컬스토리지에 저장

---

package-lock.json
package.json
src/App.js
src/index.js
src/pages/SetLogin.jsx
src/pages/TempPage.jsx
src/pages/login/Login.jsx
src/pages/main/Main.jsx
src/pages/main/Start.jsx
src/template/InitPage.jsx

리뷰해주실때  commit단위로 보시면 편하실것 같아요 : )
- App.js에서 페이지 라우팅  (url은 이슈 참고해주세요.)
- index.js에서 라우팅을 위해 BrowserRouter로 감싸주는 작업 진행
- Start.jsx  & Main.jsx 수정본 (props 추가)
-  SetLogin.jsx에서  토큰값에 따른 리다이렉션 기능 (미완)
- SetLogin.jsx를 랜더링하는 InitPage.jsx (아토믹패턴)
- TempPage.jsx : 임시페이지입니다. 
close #40

:sparkles: Add : 페이지별라우팅

---

src/App.js
src/pages/SetLogin.jsx
src/pages/main/Main.jsx
src/style/globalStyle.js

- 버튼 라우팅 
- 라우팅으로 인한 밑줄스타일링제거
- App.js에서 /main url제거 (회의시간에 알려드리겠습니당)

:sparkles: Add : 로그인,회원가입버튼라우팅

---

src/App.js
src/pages/login/Login.jsx
src/pages/main/Main.jsx

- 로그인페이지 밑 이메일로회원가입 버튼 라우팅
- 로그인 버튼을 눌렀을때 성공메시지를 받으면 임시페이지로 이동

:sparkles: Add : 누락된라우팅추가

---

src/App.js
src/components/button/Button.jsx
src/components/profile/Profile.jsx
src/pages/signUp/ProfilePage.jsx
src/pages/signUp/SignUp.jsx
src/pages/signUp/SignUpMain.jsx

- 함수 명 변경( postData -> signUp / postImgData -> imgUpload )
- postData(file) 매개변수로 이미지 값 받아오던 코드 개선 
( userData 전역변수로 분리, 이미지 값에 ImgUpload함수의 return값을 저장해주는 방식으로 변경 )
- signUp 함수 (기존 postData)에 이미지 업로드 함수 호출하여 회원 가입 로직 한번에 관리 (구조 변경)
- 이미지 업로드 함수(ImgUpload) 재 사용을 위해 따로 위쪽으로 빼냈습니다. 
close #48 close #49

:recycle: Modify : 회원가입 코드 전체적으로 개선

---

src/components/button/Button.jsx
src/components/button/buttonStyle.js
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js

- 5가지 Nav컴포넌트 생성
- 재사용컴포넌트 수정( **SaveBtn , SearchInput** : 오른쪽 정렬을 위한 props추가)
- 푸쉬를 하고 테스트용 style값 적용된게 보고 수정했습니다ㅜㅜ 커밋 상관하지 마시고 Files  changed만 보셔도 됩니당 : )

:lipstick: Style : Nav컴포넌트생성

---

package-lock.json
package.json
src/components/button/Button.jsx
src/components/errorMessage/errorMessage.jsx
src/components/input/Input.jsx
src/pages/signUp/ProfilePage.jsx
src/pages/signUp/SignUp.jsx
src/pages/signUp/SignUpMain.jsx

API통신을 통해 회원가입 페이지 유효성 검사를 진행하기 전에
1차적으로 React Hook Form 라이브러리를 사용하여 유효성 검사를 진행하는 기능 구현
* 빈칸이 허용되지 않는 필수 요소(required) - 이메일, 비밀번호, 사용자이름, 계정ID
* 이메일 형식(예시. test@gmail.com)이 올바른지
* 비밀번호 6자리 이상인지
* 사용자 이름 2-10자이내인지
* 계정ID는 영문, 숫자, 밑줄, 마침표만 사용하는지
* 버튼을 활성화하여 다음페이지로 이동 가능하도록 구현
close #37

✨ Feat : 회원가입 페이지 유효성 검사

---

src/components/deleteAlert/DeleteAlert.jsx
src/components/deleteAlert/deleteStyle.js

delete-alert 컴포넌트생성
- 폴더구조
- 피그마상에는 바깥 border가 없는데 저희는 흰배경이라 필요할것같아 일단 해놨습니당
- preview  (마진0이라 캡쳐가 힘드네욤 ㅎ.ㅎ,,)

:lipstick: Style : delete-alert 컴포넌트생성

---

src/components/button/Button.jsx
src/components/input/Input.jsx
src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js
src/pages/SignUpMain.jsx
src/style/commonLoginStyle.js
src/template/profile/ProfileSet.jsx
src/template/profileModify/ProfileModify.jsx
src/template/signUp/ProfilePage.jsx

- 내 프로필 수정 ( 이름, 계정Id, 소개글 ) 부분 구현했습니다.
- 아직 토큰값 받아오는 부분과 저장버튼 막는부분은 구현하지 않았습니다
추후 업데이트 예정입니다!
- nav 가운데 정렬 코드 추가
- MainStyle 상하 패딩 30추가, 타이틀 마진 탑 제거
-> 좌우 패딩이 있는경우 상단 또한 패딩이 존재하여 타이틀에 있던 마진탑을 제거하고 메인 스타일의 상하 패딩을 추가하였습니다.

🚧 Feat : 프로필 수정 기능 구현 중

---

src/template/signUp/ProfilePage.jsx

- props값의 setName중 e가 누락되었습니다.

:pencil2: Modify : 누락된글자추가

---

src/template/profile/ProfileSet.jsx

ProfileSet.jsx에서 import한 컴포넌트 경로 수정

:pencil2: Feat/컴포넌트경로수정

---

src/components/iconButton/IconButton.jsx
src/components/iconButton/iconButton.js

- 오른쪽정렬,cursor:pointer 넣은 아이콘버튼컴포넌트 만들었습니다.
- 자세한 사항은 이슈 참고해주세요!
close #78

:lipstick: Style : 아이콘버튼컴포넌트생성

---

src/components/button/Button.jsx
src/components/tabMenu/TabMenu.jsx
src/components/tabMenu/tabMenuStyle.js
src/components/user/User.jsx
src/template/follow/Follow.jsx
src/template/follow/followStyle.js

팔로우 목록 리스트 UI구현 완료했습니다.
back icon은 클릭했을 때 아무런 이벤트 없습니다!
- 팔로우 리스트에서 필요한 컴포넌트 스타일 수정
1. user에 프롭스 추가
2. 버튼 : follow버튼 클릭 시 콘솔로그 제거 ( 프리티어 충돌로 공백 수정 돼있어 여기 파일은 리뷰 안보셔도 될 것 같습니다 )
3. 탭메뉴
탭메뉴 랜더링안되던 오류해결, 스타일 변경
close #81

:lipstick: Style : 팔로우 리스트 UI구현 및 필요한 컴포넌트 속성 수정

---

src/pages/Homepage.jsx
src/style/commonStyle.js
src/template/TempPage.jsx
src/template/follow/Follow.jsx
src/template/follow/followStyle.js
src/template/login/Login.jsx
src/template/main/Main.jsx
src/template/main/Start.jsx
src/template/profileModify/ProfileModify.jsx
src/template/signUp/ProfilePage.jsx
src/template/signUp/SignUp.jsx

- 전체를 감싸는 AllWrap 스타일 컴포넌트 추가 
( 높이, 넓이 , 가운데 정렬 정해져 있는 공통 스타일 컴포넌트입니다)
- 불필요한 코드 삭제 
- NonPaddingMain 스타일이 AllWrap추가로 인해 불필요하게 되었습니다. PaddingMain만 남겨져 있는 상태이며 패딩이 없는 메인을 사용할 떄는 일반 html태그인 <main/> 태그를 사용하시거나 해당 페이지에서 스타일 컴포넌트를 직접 만들어 이용하면 될 것 같습니다.

💄Style :  전체적인 공통 스타일 수정

---

src/components/button/Button.jsx
src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js
src/template/profileModify/ProfileModify.jsx

- 유효성 검사 통과 못했을 경우 저장 버튼 비활성화 추가
- 네비 텍스트 부분 h1태그로 수정 및 오타 수정

:construction: Add : 유효성 불충족시 저장버튼 비활성화

---

src/pages/FeedPage.jsx

- 피드페이지 UI 만들었습니다 !!  (home아니예용 ㅎㅎ)

:lipstick: Style : 피드페이지 UI

---

src/components/imgUploadBox/ImgUploadBox.jsx
src/components/imgUploadBox/imgUploadBoxStyle.js

- 포스팅페이지에 있는 이미지 등록 박스를 컴포넌트화 했습니다.
(return시 코드가 길어져 가독성이 안좋아질것 같아서요!)
close #92

:lipstick: Style : imgUploadBox컴포넌트

---

src/template/post/AddPost.jsx

- 포스팅을 작성하는 UI를 제작했습니다.
질문
1. 현재 input태그들을 공통스타일인    `<FormStyle>` 로 묶어 갭을 주고있는데  input태그만을 form태그로 묶어도 괜찮나요 ?? form태그를 사용할때는 정보를 제출하기 위한 큰 틀?을 묶는걸루 알고있어서요!  `fieldset`같은걸 써야하지 않나 싶어서 여쭙니다! 
- **mdn fieldset** https://developer.mozilla.org/ko/docs/Web/HTML/Element/fieldset
2. 현재   ` <SaveNav/>`가 프로필 정보 저장으로 props가 설정이 되어있더라구요!
이 페이지에서도   ` <SaveNav/>`가 공통으로 사용되어서요.
재사용성을 고려하자면 props 네이밍을 바꿔야 할 것 같고,  그게 아니라면 같은 UI에 props로 받는 매개변수만 다른 함수를 만들어야 할 것 같은데 어떤게 더 낫다 생각하시나요 ? (저는 개인적으로 전자가 나을것같긴한데 의견부탁드려욤! )
.
.
.
시간 input 뺏습니당

:lipstick: Style : 포스팅작성UI

---

src/App.js
src/pages/InitPage.jsx
src/template/login/Login.jsx

- 임시페이지였던 부분 homepage로 라우팅 했습니다.
- 페이지 업데이트 될 때마다 계속 라우팅 할 예정이니 일단 승인하시지 않으셔도 됩니다 : )

:sparkles: Feat : homepage라우팅 (승인하셔도 됩니당,, 깃그래프가 너무 길어질것같아서 ㅎㅎ)

---

src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js
src/template/post/AddPost.jsx
src/template/profileModify/ProfileModify.jsx

- AllWrap의 수정에 다른 nav width값 100%으로 변경 
- 저장nav분할
`ProfileSaveNav` 와 `PostSaveNav`로 변경

:lipstick: Style : nav수정 (width값,saveNav분할)

---

src/components/tabMenu/tabMenuStyle.js

:lipstick: Style : tabMenu width수정

---

package-lock.json
package.json
src/index.js
src/reducers/Reducer.js
src/store.js

- 포스팅작성기능 구현을 위한 redux-toolkit 셋팅
-  store생성, reducer생성, index.js셋팅
- 리덕스툴킷 설치에 따른 package파일들

:sparkles: Feat : 포스팅작성redux셋팅

---

src/components/search/AccountSearchBar.jsx
src/template/search/AccountSearch.jsx

- 홈 -> 계정 검색에 해당하는 search 페이지 구현 했습니다.
- src/components/search/AccountSearchBar.jsx
- src/template/search/AccountSearch.jsx
close #104

:lipstick: Style : 계정 검색 페이지 UI 구현

---

src/components/postModal/PostModal.jsx
src/components/postModal/postModalStyle.js

* 추후 페이지 구현시 AllWrap으로 감싸일 경우를 위하여 width: 100%로 설정
* 모달 안에 있는 리스트버튼은 hover되었을 경우 폰트색상을 변화시킴으로서 가시적으로 부각됨
* 일반 리스트버튼 : hover시 폰트 색상이 #002D7D으로 변화 
* 삭제 / 로그아웃 버튼 :  hover시 폰트 색상이  #FF2F7A으로 변화 
* 신고하기 버튼 :  hover안할 경우에도 기본폰트 색상이 #FF2F7A이므로 hover시 폰트 색상은 유지하되, 폰트 굵기 600으로 변화
close #109

:lipstick: Style : 모달 컴포넌트 구현

---

src/components/button/Button.jsx
src/pages/MyProfilePage.jsx
src/template/profile/MyProfile.jsx
src/template/profileModify/ProfileModify.jsx

:lipstick: Style : 프로필페이지 구현 및 세부 스타일 변경

---

src/App.js
src/components/followCompo/FollowCompo.jsx
src/components/input/inputStyle.js
src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js
src/pages/HomePage.jsx

**1commit**
- 라우팅중 스타일 변경건이 생겨 수정합니다.
- wrapper가 브라우저 크기에 따라 변화함에 따라 input창도 `width:100%` 해주었습니다.
- Nav를  flex로 배치하는것으로 바꿨습니다.  (생각나서 다시 해보니 수정이 되더라구요?!) 
**2commit**
- `/home` , `/post` 페이지에 있는 버튼들 라우팅

:lipstick: Style : nav,input수정

---

src/pages/HomePage.jsx
src/reducers/getPetInfoSlice.js
src/template/post/HomePost.jsx
src/template/walkingFeed/DefaultFeed.jsx

- 버튼렌더링방식 변경해서 글이 있을경우,없을경우 모두 보이게 처리했습니다. 
- li를 ul로 묶어주었습니다.
- 날짜만 나오게  스트링 잘랐습니다.

:recycle: Feat : 버튼렌더링방식변경

---

src/App.js
src/components/postModal/postModalStyle.js
src/components/tabMenu/TabMenu.jsx
src/components/user/userStyle.js
src/style/commonStyle.js
src/template/chat/ChatList.jsx
src/template/walkingFeed/WalkingFeed.jsx
src/template/walkingFeed/walkingFeedStyle.js

1commit
- 게시글 스크롤 일어날 때 nav,tab고정안되는 오류 해결
-  채팅 라우터 연결 
- 모달 세부스타일 수정 ( 애니메이션속도, 배경 불투명도 )
2commit
- 스크롤메인 공통컴포넌트로 등록
- chatlist에도 적용
close #124

:adhesive_bandage: Modify : 게시글 리스트 nav,tab고정 및 세부사항 수정

---

src/components/profileIcon/ProfileIcon.jsx
src/components/user/User.jsx
src/template/post/HomePost.jsx

- 피드작성자의 프로필사진 및 이름,id 값이 렌더링 되도록 추가하였습니다.
- 디폴트이미지가 감귤마켓사진일경우 (즉, 사용자가 프로필 설정으로 한 이미지가 없다면) 임의로 저희 로고사진이 프로필사진으로 렌더링 되게 변경해줬습니다.

:sparkles: Add : 피드작성자 프로필정보 및 사진등록

---

src/components/profile/Profile.jsx
src/template/post/homePostStyle.js
src/template/profile/MyProfile.jsx
src/template/profileModify/ProfileModify.jsx

- 프로필 수정 기능 구현
: 일단 이름, 아이디, 소개 모두 수정 가능합니다! 
그러나 아이디를 수정하게 되면 API에서 아이디 값을 사용하기 때문에 뒤로가기 했을 경우 에러가 납니다...  아이디 수정 불가능하게 막다가 에러 나서 일단 다 되돌리고 여기까지 푸시 할게요!
- 내 프로필에 내 정보 불러오기  
close #85

:construction: Feat : 프로필수정기능 구현 및 회원정보 불러오기

---

src/components/tabMenu/TabMenu.jsx
src/components/tabMenu/tabMenuStyle.js

:lipstick: Add : 탭메뉴 선택시 배경컬러 고정기능 추가

---

src/pages/HomePage.jsx
src/pages/InitPage.jsx
src/reducers/getPetInfoSlice.js
src/template/login/Login.jsx
src/template/post/AddPost.jsx
src/template/profile/MyProfile.jsx
src/template/profileModify/ProfileModify.jsx

- 기존 userinfo를 모두 저장하는 코드에서, accountname과 token만 저장하는 방식으로 바꿨습니다.

:sparkles: Modify : 로컬스토리지의 저장정보 변경

---

src/App.js
src/components/button/Button.jsx
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/components/navBack/NavBack.jsx
src/components/tabMenu/tabMenuStyle.js
src/pages/SignUpMain.jsx
src/template/login/Login.jsx
src/template/post/AddPost.jsx
src/template/post/HomePost.jsx
src/template/profile/MyProfile.jsx
src/template/profile/ProfileSet.jsx
src/template/profileModify/ProfileModify.jsx

- 프로필 수정 후 내 프로필로 돌아왔을 때 수정사항 반영 
-  아이디 수정 제한 
- 프로필 수정 컴포넌트 분리 => input 컴포넌트에 있던 몇몇 부분들을 프롭스로 처리하고 분리하였습니다
- 프로필 수정 페이지 placeholder 적용
close #72

:sparkles: Feat : 프로필 수정 후 화면에 반영 및 아이디수정 제한

---

src/App.js
src/components/tabMenu/TabMenu.jsx
src/components/tabMenu/tabMenuStyle.js
src/template/chat/ChatList.jsx
src/template/follow/Follow.jsx
src/template/follow/followStyle.js
src/template/profile/MyProfile.jsx

- 팔로우, 채팅방 라우터 연결
- 팔로잉, 팔로우 일단 모두 같은페이지로 연결해놨습니다 팔로우기능 구현하시면서 변경하시면 될 것 같습니당

:lipstick: Modify : 누락된 라우터연결

---

src/template/post/HomePost.jsx

:bug: Feat : 프로필사진url경로수정

---

src/components/button/Button.jsx
src/components/button/buttonStyle.js
src/components/navBack/NavBack.jsx
src/components/speechBubble/speechBubbleStyle.js

* Button의 오른쪽 정렬을 위해 margin-left: auto를 설정함
* 이에 따라 Button컴포넌트의 props중 하나인 right의 필요성이 무의미해졌기 때문에 해당부분 삭제
* 말풍선 컴포넌트에서 MyChat의 배경색과 글자색을 추가로 설정
close #142

:lipstick: Modify : NavWrapper관련 컴포넌트 속성 수정

---

src/pages/SignUpMain.jsx
src/template/signUp/ProfilePage.jsx

- 회원가입 후 바로 로그인 페이지로 연결 
- 회원가입 시 Id검증 메세지 출력 안되는 오류 해결

:sparkles: Add : 회원가입 후 로그인페이지로 연결 및 Id검증 오류해결

---

src/template/snsPost/AddSnsPost.jsx

- `/feedpage`에서 게시글을 추가하면 추가된 게시물이 바로 업데이트 되어 보이도록 수정했습니다.
- `dispatch`를 사용하여  업로드버튼을 누르면 get요청이 가도록 설정했습니다.

:sparkles: Feat : sns게시글 추가 후 업데이트된 상태렌더링

---

src/components/animalBox/AnimalBox.jsx
src/components/animalBox/animalStyle.js
src/components/button/Button.jsx
src/components/button/buttonStyle.js
src/components/comment/commentStyle.js
src/components/deleteAlert/deleteStyle.js
src/components/errorMessage/errorStyle.js
src/components/followCompo/followCompoStyle.js
src/components/imgUploadBox/imgUploadBoxStyle.js
src/components/input/inputStyle.js
src/components/navBack/navBackStyle.js
src/components/postModal/postModalStyle.js
src/components/profileIcon/profileIconStyle.js
src/components/speechBubble/speechBubbleStyle.js
src/components/tabMenu/tabMenuStyle.js
src/components/user/userStyle.js
src/style/globalColor.js
src/template/chat/chatRoomStyle.js
src/template/follow/Follow.jsx
src/template/login/loginStyle.js
src/template/post/homePostStyle.js
src/template/profile/ProfileStyle.js
src/template/profilePost/petPostStyle.js
src/template/signUp/profilePageStyle.js
src/template/snsPost/snsPostStyle.js

전체 색상 컬러 변수화 및 전체 반영했습니다.
한번밖에 안 나오는 비슷한 컬러는 대체히였으며 채팅리스트에서 활성화 컬러 노란색 -> 저희 서브 컬러로 변경하였습니다.
최종 컬러 리스트입니다.
사용하실 때는 palette import 후 사용하시면 됩니다! 
close #50

♻️ Style :전체 컬러 색상코드 변수화 시켜서 반영

---

src/App.js
src/components/followCompo/FollowCompo.jsx

Reverts Pet-Mate-Project/Pet-Mate#166

Revert ":sparkles: Feat : url로 직접 접근시 조건부렌더링"

---

src/components/deleteAlert/DeleteAlert.jsx

:sparkles: Feat : 로그아웃 클릭시 로컬스토리지에서 값 삭제

---

src/App.js
src/pages/YourProfilePage.jsx
src/template/profile/YourProfile.jsx
src/template/search/AccountSearch.jsx

검색 리스트 클릭했을 경우 해당 유저 프로필로 연결
일단 유저 프로필 하단 랜더링은 추후 구현할 예정이며 
버튼 깨지는 부분은 세영님 코드와 합치기로 하였습니다!

:sparkles: Feat : 검색리스트와 유저프로필 연결

---

src/components/animalBox/AnimalBox.jsx
src/components/navBack/NavBack.jsx
src/components/postModal/postModalStyle.js
src/template/profilePost/PetPost.jsx

- 내 프로필 pet게시글 클릭시 토글UI 구현 
-  토글 시간 0.3s로 줄임 
-  코드 리펙토링
**[preview]**
삭제 기능 먼저 구현하겠습니다!

:lipstick: 내 프로필 pet게시글 클릭시 토글UI 구현

---

src/components/button/Button.jsx
src/components/button/buttonStyle.js
src/template/profile/YourProfile.jsx

* 팔로우, 언팔로우 버튼 클릭시 프로필 화면에 follow, following의 수가 변하도록 구현
* 버튼 스타일이 margin-left: auto로 인해 옆으로 치우쳐지는 부분 예외처리.
close #186

:sparkles: Feat : 팔로우, 언팔로우 기능 구현

---

src/components/input/Input.jsx
src/components/profile/Profile.jsx

- 프로필 수정 들어가면 바로 기존 프로필이 랜더링 되도록 기본 값 설정했습니다.

:bug: Modify : 내프로필 사진 기본값 설정안되던 버그 해결

---

src/template/profilePost/SnsAlbum.jsx

여러장을 올렸을 경우 첫 사진만 랜더링 되도록 수정하였습니다.

🐛 Modify : 내 프로필 앨범 형에서 여러 장의 사진 랜더링 안되는 오류 해결 

---

src/template/search/AccountSearch.jsx

- User 컴포넌트 `user.image` props 추가하였습니다.
추가 전
추가 후
close #195

:adhesive_bandage: Feat : 검색 페이지 이미지 props 추가

---

src/pages/YourProfilePage.jsx
src/template/search/AccountSearch.jsx

내 프로필이 아닌 다른 유저프로필을 클릭했을 경우 
등록된 펫 게시글과 SNS 게시글 랜더링 구현 완료 하였습니다.
close #180

:sparkles: Feat : 유저프로필 게시글 랜더링

---

src/pages/FeedPage.jsx
src/template/snsPost/SnsPost.jsx

피드 게시판에 내가 팔로우한 사람들의 게시글이 랜더링 되도록 구현

:sparkles: Feat : 피드게시판에 팔로워 게시글 랜더링

---

src/pages/YourProfilePage.jsx
src/template/profilePost/MyProfileSnsPost.jsx
src/template/profilePost/PetPost.jsx
src/template/snsPost/SnsPost.jsx

- 남의 게시글에서 (삭제,수정)토글 안보이게 수정했습니다. 
- sns피드같은경우 남의 게시글의 : 을 눌렀을때 신고하기 토글이 나오는데 이 기능은 미뤄두겠습니다,, ^_^

:bug: Mofify : 남의 게시글에서 (삭제,수정)토글 안보이게 수정

---

src/components/user/User.jsx
src/components/user/userStyle.js

* 피드 게시글에서 유저이미지, 유저이름, 유저아이디 쪽 클릭시 
해당 유저의 프로필로 이동하도록 라우팅 설정 및 코드 추가
close #209

:sparkles: Add : 피드 게시글 클릭시 해당 유저 프로필로 이동

---

src/pages/YourProfilePage.jsx
src/template/profilePost/MyProfileSnsPost.jsx
src/template/profilePost/PetPost.jsx
src/template/snsPost/SnsPost.jsx

Reverts Pet-Mate-Project/Pet-Mate#207
- 버그를 잡았더니 또 다른 버그가 ~! ㅎㅎㅎㅎㅎㅎ

Revert ":bug: Mofify : 남의 게시글에서 (삭제,수정)토글 안보이게 수정"

---

src/components/user/User.jsx

* 프로필로 이동하는 Link에서 전달인자의 유무 문제로 생기는 버그를 막히 위해 예외처리 추가
close #215

:bug: Modify : 프로필로 이동시 생기는 버그 수정

---

src/components/input/Input.jsx
src/components/input/inputStyle.js

:lipstick: Style : pet정보 input폼 textarea로 변경

---

src/template/post/AddPost.jsx
src/template/snsPost/AddSnsPost.jsx

- 사진업로드시 총 사진의 용량이 10MB이내로 가능하도록 설정

:bug: Feat : 사진파일 크기 제한

---

src/template/main/Main.jsx
src/template/post/HomePost.jsx
src/template/profilePost/PetPost.jsx
src/template/snsPost/SnsPost.jsx

- react key error해결했습니다.
close #224

:bug: Feat : react key error 해결

---

src/components/input/Input.jsx
src/components/input/inputStyle.js

Reverts Pet-Mate-Project/Pet-Mate#219

Revert ":lipstick: Style : pet정보 input폼 textarea로 변경"

---

src/App.js
src/components/deleteAlert/DeleteAlert.jsx
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/pages/HomePage.jsx
src/pages/MyProfilePage.jsx
src/reducers/getFollowSlice.js
src/reducers/getPetInfoSlice.js
src/reducers/getPostSlice.js
src/template/post/AddPost.jsx
src/template/postModify/PostModify.jsx
src/template/snsPost/AddSnsPost.jsx
src/template/snsPostModify/SnsPostModify.jsx

- critical하지 않은 수정
1. path변수명 수정 ( 복붙에서 사용해서 대부분 path가 `loginReqPath` 라고 되어있더라구요!)
2. Slice에서 status값 수정 (성공시 success)
3. 그밖의 줄바꿈 , 필요없는  `import`값 제거

Feat/textarea컴포넌트 생성 및 변수명등 크리티컬하지 않은 수정

---

src/components/user/User.jsx

* UserChat 영역 클릭시 프로필로 이동할 수 있도록 라우팅 추가
* User.jsx파일 내 조건식2개를 삼항연산자로 통합
close #229

:art: Modify : 코드 개선 및 라우팅 추가

---

README.md

- 임시 메인 이미지 추가하였습니다.
- 프로젝트 소개 내용 추가하였습니다.
- 팀원 소개 이미지는 깃허브 프로필 이미지로 추가하였습니다.
close #231

:memo: Modify : 기본 내용 추가

---

src/App.js
src/pages/HomePage.jsx
src/reducers/getAllpetInfoSlice.js
src/reducers/getPetInfoSlice.js
src/store.js

- 모든 페이지를 불러오는 `Slice`인 `getAllpetInfoSlice` 를 추가하였습니다.
- 이에 따라 Homepage에서 사용하던 기존 `getPetInfoSlice`에서 값을 가져오는 코드를 삭제했습니다.
**[주의]**
- store의 값이 동일하게 있는 값을 제외한 나머지 (다른 ReqPath를 요청하는 Axios코드)를 사용하시는 경우 새로운 Slice를 만드셔서 사용하시는게 좋을 것 같습니다! 
- 혹시 RTK코드를 사용하셔야 하는데 사용하시는 법이 어려우실때 제가 말씀해 주시면 알려드리겠습니다~!

Feat : RTK 공통slice를 이용해 생긴 버그잡기

---

src/components/button/Button.jsx
src/template/homePost/HomePost.jsx
src/template/homePost/homePostStyle.js

홈 피드 스타일 리스트 형으로 변경
close #240

:lipstick: Style : 홈피드 스타일 변경

---

src/components/post/FeedPost.jsx

- UI만 동작하는 토글 좋아요 버튼 구현입니다.
- 자세히 보기 클릭부분과 클릭하는 영역이 겹쳐 사진을 재렌더링 시켜 깜빡입니다. 이 부분 수정해야 할 것 같습니다!

:lipstick: Style : 좋아요토글UI

---

src/template/postDetail/FeedPostDetail.jsx

* 옵셔널 체이닝을 통해 에러 수정
close #246

:bug: Modify : 게시글 정보가 저장된  postDetail이 undefined일 때 생기는 에러 수정

---

src/store.js

- store에 import하는 명칭 통일 (reducer로)
- 원래 다른곳 건들이려 했는데 ㅜㅜ 막 건들이다가 충돌나서,, 일단 이것만 푸시하고 브랜치 강제로 지우려고,, 푸시했습니다 흑

:truck: Feat : store에 import하는 명칭 통일 (reducer로)

---

src/components/user/User.jsx
src/template/profile/YourProfile.jsx

* follow관련된 곳에서 팔로우의 유무를 판단하는 isFollow변수가 초기값으로 false로 설정되어있는데
* 이 때문에 팔로워, 팔로잉 리스트에 들어갔을때 버튼이 false로 첫랜더링이 되다가
실제 팔로워 유무에 따른 값으로 재랜더링 되는 문제 해결
<버그 수정 전>
<버그 수정 후>
close #202

:bug: Modify : 팔로워, 팔로잉 리스트에 들어갔을 때 첫랜더링 문제로 버튼이 깜박이는 이슈 해결

---

package-lock.json
package.json
src/pages/HomePage.jsx

- 홈 로딩바 구현
- 아래와 같습니당
**[추가]**
- 현재 홈에서 많은 게시글들을 불러와 렌더링 속도가 평균 5초를 넘어갑니다.. ㅜㅜ
- 찾아보니 3초이상 로딩되는 웹에서는 사용자가 이탈하는 퍼센트가 높아진다고 하더라구요.
- 라이브러리를 알아보니 `react-window` 와 `react-virtualized`가 있습니다. 다만 둘다 css를 직접 import하는 방식으로 돌아가는것 같더라구요. 일단 최적화 부분에 대해 여러방면으로 알아보겠습니다 !

:sparkles: Feat : 홈 로딩바 구현

---

src/components/post/FeedPost.jsx
src/pages/FeedPage.jsx

Sns 피드 게시글 클릭했을 때 좋아요 기능 구현 및 불필요한 코드 삭제

✨ Feat : 좋아요 기능 구현 

---

src/components/post/FeedPost.jsx
src/template/snsPost/SnsPost.jsx

1commit
user프로필에 sns게시글 랜더링 안되는 오류 해결
2commit
sns피드에서 누른 좋아요가 상세페이지에서는 반영 안되는 오류 해결

Modify : 오류수정

---

src/reducers/getCommentSlice.js
src/template/postDetail/FeedPostDetail.jsx

- 댓글이 실시간으로 업데이트되지 않는 동작 수정
- `CommentList`의 `status`값이 loading중일때 `dispatch`하는 코드를 추가
(한 40개정도 테스트 해봤는데 저는 업데이트가 잘 되었지만 혹시 업데이트 에러 나면 말씀해주세요!! ㅜㅡㅜ)

:bug: Feat : 댓글업데이트 버그 수정

---

src/components/comment/Comment.jsx
src/components/commentList/CommentList.jsx
src/components/deleteAlert/DeleteAlert.jsx
src/reducers/getCommentSlice.js
src/template/postDetail/FeedPostDetail.jsx

- 자신의 댓글이라면 삭제를, 아니면 신고버튼을 나오도록 설정
- 댓글이 많아지면 (추측으로 50개이상,,?) 토글버튼이 나올때 검정색으로 나오는데.. 이건 추후에 고쳐보겠습니다ㅜㅜ
- 일단 다른 버그들 먼저 수정하겠습니다.

:sparkles: Feat : 댓글토글버튼구현

---

src/components/commentList/CommentList.jsx
src/template/postDetail/FeedPostDetail.jsx
src/template/profilePost/PetPost.jsx

- 댓글 리스트 컴포넌트에서 토글을 return하고 있어서 나오는 오류였습니다.. (토글이 겹치면서 검정색으로,,)
- 또한 버튼이 중복되어있어 생기는 콘솔오류잡았습니다.

:bug: Feat : 토글배경 검정색으로 나오는 오류

---

src/components/commentList/CommentList.jsx
src/components/post/FeedPost.jsx
src/components/user/User.jsx
src/template/homePost/HomePost.jsx
src/template/postDetail/FeedPostDetail.jsx
src/template/postDetail/WalkingPostDetail.jsx
src/template/profile/MyProfile.jsx
src/template/profile/YourProfile.jsx
src/template/profilePost/PetPost.jsx

* 이미지를 base64로 인코딩하여 업로드하는 팀, 인코딩없이 로컬 이미지 파일 주소만 업로드 하는 팀, 인코딩없이 서버주소+로컬 이미지 파일 주소 업로드하는 팀 등등 다양한 방식 때문에 이미지가 안뜨는 경우에 대해 예외처리
<br>
close #278

:bug: Modify : 팀마다 이미지 업로드 방식이 다양하여 이미지가 안뜨는 이슈 수정

---

src/components/animalBox/AnimalBox.jsx
src/components/commentList/CommentList.jsx
src/components/iconButton/IconButton.jsx
src/components/navBack/NavBack.jsx
src/components/post/FeedPost.jsx
src/components/profileIcon/ProfileIcon.jsx
src/components/user/User.jsx
src/components/user/userStyle.js
src/template/homePost/HomePost.jsx
src/template/profilePost/MyProfileSnsPost.jsx
src/template/profilePost/PetPost.jsx
src/template/profilePost/myProfileSnsPostStyle.js

- 접근성을 위한 코드 리팩토링
- 색상대비
- 이미지 alt값
- 버튼의 텍스트가 없을경우 이미지를 사용하고 `button`태그로 감싸기

:recycle: Feat : 접근성을 위한 코드 리팩토링

---

src/pages/InitPage.jsx
src/reducers/verifyTokenSlice.js
src/store.js

- 기존은 단순히 로컬스토리지에서 token값을 꺼내오는 코드였기 때문에 에러가 난다는 피드백 접수
- 첫 접속시 토큰검증 API를 사용한 검증을 통해 토큰값이 없다면 API요청을 보내지 않고, 결과값도 리턴하지 않도록 수정
close #281

:bug: Feat : 첫 접속시 토큰검증API를 사용하여 검증

---

src/components/imgUploadBox/ImgUploadBox.jsx
src/components/imgUploadBox/imgUploadBoxStyle.js

- 기존 게시글 업로드시 이미지 src가 안들어온채 렌더링 되어 alt값이 띄워져 있었던 부분을 수정하였습니다.

:bug: Feat : 기존 게시글 업로드시 이미지 src가 안들어온채 렌더링된 부분 수정

---

src/components/errorMessage/errorStyle.js
src/components/input/inputStyle.js
src/style/commonStyle.js
src/style/globalStyle.js
src/template/login/Login.jsx
src/template/login/loginStyle.js
src/template/profile/ProfileSet.jsx
src/template/search/AccountSearch.jsx
src/template/signUp/SignUp.jsx

* 웹상에서는 input창이 작은 느낌이 있어서 미디어쿼리를 사용하여 웹에서는 적절한 사이즈로 보일 수 있도록 수정하였음
close #289

:lipstick: Style : 로그인/회원가입에서 input 및 글자 크기 조정

---

src/template/postDetail/FeedPostDetail.jsx

코드가 주석처리되어있어서 댓글 자동으로 업로드 안되는 문제 해결

:adhesive_bandage: Modify : 주석처리된 코드때문에 댓글 자동으로 업로드 안되는 문제 해결

---

src/template/homePost/AddPost.jsx

:adhesive_bandage: Modify : 이미지 경로 변경

---

src/components/post/FeedPost.jsx

내프로필에서 디테일페이지 댓글달면 랜더링 안되는 오류 해결

:adhesive_bandage: Modify : 내프로필에서 디테일페이지 댓글 달면 랜더링 안되는 오류해결

---

src/components/profileIcon/ProfileIcon.jsx
src/style/commonStyle.js
src/template/follow/MyFollow.jsx
src/template/follow/YourFollow.jsx
src/template/follow/followStyle.js

* 그 동안 myprofile과 yourprofile에 있는 follower리스트와 following리스트에 제한을 두지 않아서 유저리스트가 최대 10개까지밖에 뜨지않았는데, 이 제한을 1000개로 확장했습니다
* 웹버전일때 유저리스트 간격이 좁다는 들어 미디어쿼리를 사용하여 gap간격을 늘렸습니다
<br>
close #298

:lipstick: Modify : 팔로우리스트 limit 제한 및 스타일 수정

---

src/template/postDetail/FeedPostDetail.jsx

-  댓글리스 트렌더링시 이전 댓글이 잠깐 보이는 현상 제거
- 일단 제가 한 40번정도 확인해 봤을땐 안나왔는데 같이 테스트 해주시면 감사하겠습니다 ㅎㅎ

:bug: Feat : 댓글리스트렌더링시 이전 댓글이 잠깐 보이는 현상 제거

---

src/components/input/Input.jsx
src/pages/SignUpMain.jsx
src/template/signUp/SignUp.jsx

- 회원가입 페이지에서 비밀번호 확인 Input을 추가하여 비밀번호와 비밀번호 확인 입력값이 일치하지 않으면 다음으로 넘어가지 않고 에러메시지를 출력하도록 구현하였습니다.
- 다음 버튼을 누르지 않아도 입력한 비밀번호 값이 서로 일치하지 않음을 메시지 출력을 통해 사용자에게 빠른 피드백을 줄 수 있도록 하였습니다. (사용자 경험 개선)
- 맞춤법(띄어쓰기) 
1. `"입력해주세요."` -> `"입력해 주세요."`
2. `"입력사항"` -> `"입력 사항"`
<br>
close #301

Feat : 회원가입 비밀번호 확인 기능 추가

---

src/components/imgUploadBox/ImgUploadBox.jsx

:adhesive_bandage: Feat : import안된 컴포넌트 import

---

src/pages/FeedPage.jsx
src/pages/HomePage.jsx
src/pages/InitPage.jsx
src/pages/MyProfilePage.jsx
src/pages/SignUpMain.jsx
src/pages/YourProfilePage.jsx
src/template/follow/MyFollow.jsx
src/template/follow/YourFollow.jsx
src/template/homePost/AddPost.jsx
src/template/homePost/HomePost.jsx
src/template/login/Login.jsx
src/template/main/Main.jsx
src/template/postDetail/FeedPostDetail.jsx
src/template/postDetail/WalkingPostDetail.jsx
src/template/postModify/PostModify.jsx
src/template/profile/MyProfile.jsx
src/template/profile/YourProfile.jsx
src/template/profileModify/ProfileModify.jsx
src/template/profilePost/PetPost.jsx
src/template/profilePost/SnsAlbum.jsx
src/template/search/AccountSearch.jsx
src/template/signUp/ProfilePage.jsx
src/template/signUp/SignUp.jsx
src/template/snsPost/AddSnsPost.jsx
src/template/snsPost/SnsPost.jsx
src/template/snsPostModify/SnsPostModify.jsx

코드구조 순서는 
React
{ react 관련 나머지 }
react-redux
reducers
axios
나머지는  스타일, 컴포넌트, 템플릿 등 시작 폴더가 같은 애들끼리 묶었습니다.
ex)
closed #310

:art: Modify : import코드 순서변경 및 사용되지않는 코드 삭제

---

src/components/profile/Profile.jsx
src/pages/SignUpMain.jsx
src/template/profileModify/ProfileModify.jsx

다른 마켓에서 우리 이미지 안보이는 오류 해결
프로필 이미지 전송 시 빈값이 들어왔을 때 저희 기본이미지 서버로 전송

:art: Modify : 다른 마켓에서 우리이미지 안보이는 오류 해결

---

src/components/deleteAlert/DeleteAlert.jsx
src/components/deleteAlert/deleteStyle.js

웹에서 화면 축소시 deleteAlert UI가 깨지는 현상이 있어서 수정
close #312

:adhesive_bandage: Style : 화면 축소시 deleteAlert가 깨지는 UI 수정

---

src/components/navBack/NavBack.jsx

* 팔로워 리스트, 팔로잉 리스트에서 상단 우측에 있는 더보기 버튼(점 3개)을 클릭시 뜨는 잘못된 팝업창 수정
close #314

:bug: Modify : 페이지에 안맞게 뜨는 팝업창 수정

---

src/template/postModify/PostModify.jsx
src/template/snsPostModify/SnsPostModify.jsx

- upload함수의 return값이 바뀜에 따른 코드 수정

:bug: Feat : 사진경로가 수정됨에 따른 코드 수정

---

README.md

- 대표 이미지 수정
- 기술 및 개발 환경 내용 추가
- 역할 분담 내용 추가
- 기능 구현 내용 수정
- 폴더 구조 최신화
close #322

:memo: Modify : 내용 수정

---

src/components/profile/Profile.jsx
src/template/profile/ProfileSet.jsx
src/template/profileModify/ProfileModify.jsx

코드 수정으로 인해 프로필 수정시 default값이 적용안되던 에러 해결하였습니다.
default 값이 고정 되지 않은 것이 문제였기에 fixImg(처음 아이디받아왔을때의 이미지값)를 추가해주었습니다.
closed #320

 Modify : 코드수정으로 인해 프로필수정시 default값 적용 안되던 에러 해결 

---

src/components/followCompo/FollowCompo.jsx

- 404 페이지 버튼 `이전 페이지` -> `홈으로 이동`  **수정** 하였습니다.
close #324

:lipstick: Modify : 404페이지 이전 페이지 버튼 수정

---

src/components/followCompo/FollowCompo.jsx
src/template/profile/MyProfile.jsx
src/template/profile/YourProfile.jsx

- `)`, `@` 특수문자를 `&#40;`, `&#64;`로 **수정**하였습니다.
close #328

:speech_balloon: Modify : 특수문자 수정

---

src/components/input/Input.jsx
src/style/commonStyle.js
src/template/login/Login.jsx
src/template/login/loginStyle.js

- 불필요한 컴포넌트 재렌더링 막기 (login페이지)
- `React.memo` 사용
- 구현중 버그가 생겨 댓글 버그 먼저 확인하겠습니다.

:recycle: Feat : 불필요한 컴포넌트 재렌더링 막기

---

src/components/profileIcon/ProfileIcon.jsx
src/template/homePost/homePostStyle.js
src/template/postDetail/FeedPostDetail.jsx
src/template/postDetail/walkingPostDetailStyle.js

- 경로 변경으로인해 댓글 이미지 UI 안뜨는 오류 발생
=> 예외처리
- 홈피드의 글자크기가 유독 너무 큰 것 같아 반응형일때 글자크기 살짝 줄였습니다
- 디테일페이지 이미지 웹버전 높이 조절하였습니다

:adhesive_bandage: Modify : 댓글 이미지 UI 예외처리

---

src/components/profile/Profile.jsx
src/components/user/User.jsx
src/template/homePost/HomePost.jsx

이미지 예외처리 항목 추가
이미지 예외처리 항목추가하여 대부분의 유저 프로필이 보이도록 변경하였습니다

:adhesive_bandage: Modify : 이미지 예외처리

---

src/components/comment/Comment.jsx
src/template/postDetail/FeedPostDetail.jsx

- 댓글이 실시간으로 달리지 않는 현상을 해결했습니다.

:bug: Feat : 댓글 업데이트 오류 수정

---

src/components/errorMessage/errorMessage.jsx
src/components/input/Input.jsx
src/template/profile/ProfileSet.jsx
src/template/signUp/ProfilePage.jsx
src/template/signUp/SignUp.jsx
src/template/signUp/profilePageStyle.js

- 회원가입 페이지에서 input값이 `onChange` 될 때마다 리렌더링 되지 않아도 될 컴포넌트들을 `memo`를 사용하여 막아주었습니다.

Feat/회원가입 페이지 리렌더링

---

src/components/animalBox/AnimalBox.jsx
src/components/commentList/CommentList.jsx
src/components/profileIcon/ProfileIcon.jsx
src/components/user/User.jsx
src/template/postDetail/FeedPostDetail.jsx
src/template/profile/MyProfile.jsx
src/template/profile/YourProfile.jsx
src/template/profilePost/PetPost.jsx
src/template/profilePost/SnsAlbum.jsx

이전 커밋에서 이미지 체크함수를 재사용 하기위해 component - user 페이지에 별도로 export 해놓았었습니다.
전체 코드를 살펴보니 이미지 체크함수를 중복으로 사용하는 페이지가 많아 중복코드 삭제 후 함수 import 하였습니다.
close #338

:art: Modfiy : 이미지체크함수 별도로 빼내서 코드 재사용

---

src/components/navBack/NavBack.jsx

- 디테일 페이지에서 뒤로가기 클릭시 `/feedpage`로 라우팅되도록 설정 (하트가 반영됨을 위해)

:sparkles: Modify : 디테일페이지 뒤로가기함수 변경

---

src/components/input/Input.jsx
src/components/tabMenu/TabMenu.jsx
src/pages/HomePage.jsx

- 회원가입 시 사용자 계정 글자 수가 총 20글자 넘어가지 않도록 하였습니다.
- 20글자 넘게 입력 시도 시, `*계정 ID는 20자 이내여야 합니다.` 메시지를 출력합니다.
<br>
close #342

Modify : 회원가입 사용자 계정 글자 수 제한

---

src/template/snsPostModify/SnsPostModify.jsx

- 기존 사진경로가 달라짐에 따라 로직을 수정하였습니다.
- 미리보기 사진만 삭제되고 실제 서버에 보내는 사진이 삭제가 안된 현상이였습니다. 
- 다른 사진들과 달리 여러사진을 올릴시에는 URL을 안붙여서 올리므로 이것 또한 수정하였습니다. 
close #349

:bug: Feat : sns게시글수정오류

---

src/components/input/Input.jsx
src/template/profile/ProfileSet.jsx

- 프로필 설정 시 소개 글자 수가 총 200글자 넘어가지 않도록 하였습니다.
- 200글자 넘게 입력 시도 시, `*프로필 소개는 200자 이내여야 합니다.` 메시지를 출력합니다.
<br>
close #353

:adhesive_bandage: Modify : 프로필 설정 소개 글자 수 제한

---

src/template/profile/ProfileSet.jsx

- 프로필 수정 시 소개 글자 수가 총 200글자 넘어가지 않도록 하였습니다.
-  200글자 넘게 입력 시도 시, `*프로필 소개는 200자 이내여야 합니다.` 메시지를 출력합니다.
colse #360

Modify : 프로필 수정 소개 글자 수 제한

---

src/template/profileModify/ProfileModify.jsx
src/template/search/AccountSearch.jsx

:recycle: Feat : 프로필수정,검색페이지 h1태그 추가

---

public/index.html

:adhesive_bandage: Modify : 사파리에서 인풋창 확대되는 현상 제거

---

src/template/chat/ChatRoom.jsx
src/template/chat/chatRoomStyle.js

:adhesive_bandage: Modify : 채팅방내용변경

---

README.md

- 1 commit
각 기능 & 홈페이지별 시연 영상 및 메인 이미지 추가
- 2commit
매칭 게시글과 SNS 게시글이 잘못 등록되어있어 변경, 채팅영상 채팅+404 시연영상으로 변경
노션에 등록되어있는 시연 영상 확인 부탁드립니다!

📝 Add : 시연영상 및 메인이미지 추가

---

README.md

- 기능 구현 내용 중 `추가 예정(~7/31)` 삭제하였습니다.
- 프로젝트 소개에 테스트 계정은 코드 블럭 처리하였습니다.

Modify : 테스트 계정 코드 블럭 처리

---

package-lock.json
package.json
src/components/commentList/CommentList.jsx
src/components/deleteAlert/DeleteAlert.jsx
src/components/post/FeedPost.jsx
src/index.js
src/pages/FeedPage.jsx
src/pages/HomePage.jsx
src/pages/MyProfilePage.jsx
src/pages/NotFoundPage.jsx
src/pages/YourProfilePage.jsx
src/template/chat/ChatList.jsx
src/template/chat/ChatRoom.jsx
src/template/follow/MyFollow.jsx
src/template/follow/YourFollow.jsx
src/template/homePost/AddPost.jsx
src/template/login/Login.jsx
src/template/postDetail/FeedPostDetail.jsx
src/template/postDetail/WalkingPostDetail.jsx
src/template/postModify/PostModify.jsx
src/template/profileModify/ProfileModify.jsx
src/template/search/AccountSearch.jsx
src/template/signUp/ProfilePage.jsx
src/template/signUp/SignUp.jsx
src/template/snsPost/AddSnsPost.jsx
src/template/snsPostModify/SnsPostModify.jsx

**1commit**
- 댓글 갯수가 삭제하자마자 업데이트 되지 않은 버그 수정
**2commit**
- SEO를 위해 각 페이지별 메타태그를 추가했습니다.
- react-helmet-async를 사용하였습니다. 
**[ 대표예시 몇가지 ]**
**3,4commit**
- 회원가입 페이지에 로그인페이지로 가는 `Link`ㄴ 추가
- 
close #372

Feat/댓글개수업데이트 오류, meta태그추가 , 로그인페이지Link추가

---

public/index.html

- 오픈 그래프 메타 태그를 추가하여 콘텐츠의 요약 내용이 SNS에 게시 될 때 최적화된 데이터를 가지고 갈 수 있도록 설정하였습니다.
<br>
close #348

:sparkles: Feat : SEO 최적화(오픈 그래프) 추가

---

src/components/animalBox/AnimalBox.jsx
src/components/animalBox/animalStyle.js
src/components/button/Button.jsx
src/components/button/buttonStyle.js
src/components/comment/Comment.jsx
src/components/comment/commentStyle.js
src/components/commentList/CommentList.jsx
src/components/commentList/commentListStlye.js
src/components/deleteAlert/DeleteAlert.jsx
src/components/deleteAlert/deleteStyle.js
src/components/errorMessage/errorMessage.jsx
src/components/errorMessage/errorStyle.js
src/components/followCompo/FollowCompo.jsx
src/components/followCompo/followCompoStyle.js
src/components/iconButton/IconButton.jsx
src/components/iconButton/iconButtonStyle.js
src/components/imgUploadBox/ImgUploadBox.jsx
src/components/imgUploadBox/imgUploadBoxStyle.js
src/components/input/Input.jsx
src/components/input/inputStyle.js
src/components/navBack/NavBack.jsx
src/components/navBack/navBackStyle.js
src/components/post/FeedPost.jsx
src/components/post/feedPostStyle.js
src/components/postModal/PostModal.jsx
src/components/postModal/postModalStyle.js

- import, 주석, 콘솔 출력 등 컨벤션에 맞춰서 정리하였습니다.

:art: Modify : components 코드 정리

---

src/components/post/FeedPost.jsx

- FeedPost.jsx 좋아요(하트이모지) 콘솔 출력 제거 하였습니다.

:art: Modify : FeedPost 콘솔 제거
